"
I am an abstract object that represent a reference made to another entity in the source code a behavioural entity.


"
Class {
	#name : 'FmxSQLReference',
	#superclass : 'FmxSQLEntity',
	#category : 'FamixNGSQL-Entities',
	#package : 'FamixNGSQL',
	#tag : 'Entities'
}

{ #category : 'meta' }
FmxSQLReference class >> annotation [

	<FMClass: #Reference super: #FmxSQLEntity>
	<package: #FamixNGSQL>
	<generated>
	^ self
]
