"
I am an abstract object that represent a reference made to another entity in the source code a behavioural entity.


"
Class {
	#name : 'FmxSQLStructReference',
	#superclass : 'FmxSQLStructEntity',
	#category : 'FamixNGSQLStruct-Entities',
	#package : 'FamixNGSQLStruct',
	#tag : 'Entities'
}

{ #category : 'meta' }
FmxSQLStructReference class >> annotation [

	<FMClass: #Reference super: #FmxSQLStructEntity>
	<package: #FamixNGSQLStruct>
	<generated>
	^ self
]
